### ISSUE TITLE
Docker build won't run succcesssfuly 

### ISSUE THREAD

**Issue by eldridgea** [nkanaev/yarr#11]
Running this using the dockerfile results in the browser getting no response, and the container returns errors like these:

```
2020/09/17 16:14:26 http: panic serving 172.17.0.1:47948: open assets/index.html: no such file or directory
goroutine 12 [running]:
net/http.(*conn).serve.func1(0xc000210320)
	/usr/local/go/src/net/http/server.go:1801 +0x147
panic(0x9f57e0, 0xc0001fb530)
	/usr/local/go/src/runtime/panic.go:975 +0x3e9
html/template.Must(...)
	/usr/local/go/src/html/template/template.go:372
github.com/nkanaev/yarr/server.IndexHandler(0xb158c0, 0xc0001be380, 0xc000228100)
	/src/server/handlers.go:99 +0x78a
github.com/nkanaev/yarr/server.Handler.ServeHTTP(0x7ffc5096696f, 0xc, 0xc000051c60, 0xc000070cd0, 0xc000067200, 0xc000212098, 0xb158c0, 0xc0001be380, 0xc000228000)
	/src/server/server.go:46 +0x222
net/http.serverHandler.ServeHTTP(0xc0001be2a0, 0xb158c0, 0xc0001be380, 0xc000228000)
	/usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc000210320, 0xb16a40, 0xc000064b40)
	/usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2969 +0x36c
```

**Comment by eldridgea** [comment]
Ah - switching the `make` parameters to just be `build_linux` seems to fix this. I'll submit a PR shortly.
