### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by adaszko** [nkanaev/yarr#144]
It’s me again ;)

I’m running yarr on arm64 and it occasionally crashes.  I enabled `export GOTRACEBACK=single` and got this:

```
fatal error: concurrent map read and map write

goroutine 3113 [running]:
github.com/nkanaev/yarr/src/server.(*Server).handleFeedIcon(0x400014ac00, 0x40003cd280)
	/Users/adaszko/repos/yarr-nanopi/src/server/routes.go:181 +0x98
github.com/nkanaev/yarr/src/server/router.(*Context).Next(...)
	/Users/adaszko/repos/yarr-nanopi/src/server/router/context.go:24
github.com/nkanaev/yarr/src/server/gzip.Middleware(0x40003cd280)
	/Users/adaszko/repos/yarr-nanopi/src/server/gzip/middleware.go:42 +0x244
github.com/nkanaev/yarr/src/server/router.(*Context).Next(...)
	/Users/adaszko/repos/yarr-nanopi/src/server/router/context.go:24
github.com/nkanaev/yarr/src/server/router.(*Router).ServeHTTP(0x400006aa80, {0x3d8d60?, 0x4000555500}, 0x400054b800)
	/Users/adaszko/repos/yarr-nanopi/src/server/router/router.go:81 +0x2b8
net/http.serverHandler.ServeHTTP({0x400059ed80?}, {0x3d8d60, 0x4000555500}, 0x400054b800)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/http/server.go:2936 +0x2c0
net/http.(*conn).serve(0x4000092090, {0x3d90d8, 0x4000304f00})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/http/server.go:1995 +0x518
created by net/http.(*Server).Serve
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/http/server.go:3089 +0x4e8

goroutine 1 [IO wait, 2 minutes]:
internal/poll.runtime_pollWait(0xffff8a7a92c8, 0x72)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/runtime/netpoll.go:306 +0xa0
internal/poll.(*pollDesc).wait(0x4000320100?, 0x0?, 0x0)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0x4000320100)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/internal/poll/fd_unix.go:614 +0x250
net.(*netFD).accept(0x4000320100)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/fd_unix.go:172 +0x28
net.(*TCPListener).accept(0x400000e2d0)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/tcpsock_posix.go:148 +0x28
net.(*TCPListener).Accept(0x400000e2d0)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/tcpsock.go:297 +0x2c
net/http.(*Server).Serve(0x40000221e0, {0x3d8b50, 0x400000e2d0})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/http/server.go:3059 +0x2cc
net/http.(*Server).ListenAndServe(0x40000221e0)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/http/server.go:2988 +0x84
github.com/nkanaev/yarr/src/server.(*Server).Start(0x400014ac00)
	/Users/adaszko/repos/yarr-nanopi/src/server/server.go:62 +0x118
github.com/nkanaev/yarr/src/platform.Start(...)
	/Users/adaszko/repos/yarr-nanopi/src/platform/guiless.go:11
main.main()
	/Users/adaszko/repos/yarr-nanopi/src/main.go:154 +0x1370

goroutine 6 [select, 5 minutes]:
database/sql.(*DB).connectionOpener(0x400010aea0, {0x3d9030, 0x40000764b0})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/database/sql/sql.go:1218 +0x80
created by database/sql.OpenDB
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/database/sql/sql.go:791 +0x170

goroutine 9 [chan receive, 5 minutes]:
github.com/nkanaev/yarr/src/worker.(*Worker).StartFeedCleaner.func1()
	/Users/adaszko/repos/yarr-nanopi/src/worker/worker.go:36 +0x34
created by github.com/nkanaev/yarr/src/worker.(*Worker).StartFeedCleaner
	/Users/adaszko/repos/yarr-nanopi/src/worker/worker.go:34 +0xc8

goroutine 10 [select, 5 minutes]:
github.com/nkanaev/yarr/src/worker.(*Worker).SetRefreshRate.func1(0x400006c4e0, 0x4000078120, 0x0?)
	/Users/adaszko/repos/yarr-nanopi/src/worker/worker.go:78 +0xe0
created by github.com/nkanaev/yarr/src/worker.(*Worker).SetRefreshRate
	/Users/adaszko/repos/yarr-nanopi/src/worker/worker.go:75 +0x1f4

goroutine 3087 [runnable]:
syscall.Syscall(0x400024f918?, 0x748bb8?, 0x80000000000?, 0x7ffff80000000000?)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/syscall/syscall_linux.go:69 +0x20
syscall.write(0x400077a080?, {0x40005f4000?, 0x400024f900?, 0x760001?})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/syscall/zsyscall_linux_arm64.go:939 +0x40
syscall.Write(...)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/syscall/syscall_unix.go:206
internal/poll.ignoringEINTRIO(...)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/internal/poll/fd_unix.go:794
internal/poll.(*FD).Write(0x400077a080, {0x40005f4000, 0x5a, 0x1000})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/internal/poll/fd_unix.go:383 +0x2c0
net.(*netFD).Write(0x400077a080, {0x40005f4000?, 0x0?, 0x0?})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/fd_posix.go:96 +0x28
net.(*conn).Write(0x4000010058, {0x40005f4000?, 0x0?, 0x0?})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/net.go:195 +0x34
net/http.checkConnErrorWriter.Write({0x400024fb38?}, {0x40005f4000?, 0x40001d77e0?, 0x0?})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/http/server.go:3598 +0x34
bufio.(*Writer).Flush(0x400027a580)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/bufio/bufio.go:628 +0x60
net/http.(*response).finishRequest(0x40001d77a0)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/http/server.go:1652 +0x74
net/http.(*conn).serve(0x40002c41b0, {0x3d90d8, 0x4000304f00})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/http/server.go:2001 +0x540
created by net/http.(*Server).Serve
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/http/server.go:3089 +0x4e8

goroutine 3116 [runnable]:
github.com/mattn/go-sqlite3._Cfunc_free(0xffff8a729610)
	_cgo_gotypes.go:396 +0x30
github.com/mattn/go-sqlite3.(*SQLiteConn).prepare.func1.1()
	/Users/adaszko/repos/yarr-nanopi/vendor/github.com/mattn/go-sqlite3/sqlite3.go:1746 +0x40
github.com/mattn/go-sqlite3.(*SQLiteConn).prepare(0x400006c360, {0x4000080000?, 0x40003f1180?}, {0x2f2cd1?, 0x40003ab018?})
	/Users/adaszko/repos/yarr-nanopi/vendor/github.com/mattn/go-sqlite3/sqlite3.go:1759 +0x180
github.com/mattn/go-sqlite3.(*SQLiteConn).query(0x1003ab148?, {0x3d9068, 0x4000024078}, {0x2f2cd1?, 0x0?}, {0x40004f6e70, 0x1, 0x1})
	/Users/adaszko/repos/yarr-nanopi/vendor/github.com/mattn/go-sqlite3/sqlite3.go:859 +0xb4
github.com/mattn/go-sqlite3.(*SQLiteConn).QueryContext(0x40003ab1b8?, {0x3d9068, 0x4000024078}, {0x2f2cd1, 0x7b}, {0x40004f6e40, 0x1, 0x6b0150?})
	/Users/adaszko/repos/yarr-nanopi/vendor/github.com/mattn/go-sqlite3/sqlite3_go18.go:32 +0x10c
database/sql.ctxDriverQuery({0x3d9068?, 0x4000024078?}, {0xffff8a7a93d8?, 0x400006c360?}, {0x0?, 0x0?}, {0x2f2cd1?, 0x40003ab3a4?}, {0x40004f6e40?, 0x676c64?, ...})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/database/sql/ctxutil.go:48 +0xac
database/sql.(*DB).queryDC.func1()
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/database/sql/sql.go:1748 +0x12c
database/sql.withLock({0x3d7280, 0x40001ae000}, 0x40003ab438)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/database/sql/sql.go:3405 +0x7c
database/sql.(*DB).queryDC(0x400010aea0?, {0x3d9068, 0x4000024078}, {0x0, 0x0}, 0x40001ae000, 0x4000281f60, {0x2f2cd1, 0x7b}, {0x40003ab758, ...})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/database/sql/sql.go:1743 +0x168
database/sql.(*DB).query(0x1?, {0x3d9068, 0x4000024078}, {0x2f2cd1, 0x7b}, {0x40003ab758, 0x1, 0x1}, 0x48?)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/database/sql/sql.go:1726 +0xb8
database/sql.(*DB).QueryContext.func1(0x0?)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/database/sql/sql.go:1704 +0x54
database/sql.(*DB).retry(0x40003ab658?, 0x40003ab630)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/database/sql/sql.go:1538 +0x4c
database/sql.(*DB).QueryContext(0xffff8a6306e8?, {0x3d9068?, 0x4000024078?}, {0x2f2cd1?, 0x40005316e0?}, {0x40003ab758?, 0x40003ab6f8?, 0x7f0690?})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/database/sql/sql.go:1703 +0x94
database/sql.(*DB).QueryRowContext(...)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/database/sql/sql.go:1804
database/sql.(*DB).QueryRow(0x40003ab700?, {0x2f2cd1?, 0x40003ab788?}, {0x40003ab758?, 0x4000305890?, 0x8?})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/database/sql/sql.go:1818 +0x4c
github.com/nkanaev/yarr/src/storage.(*Storage).GetFeed(0x40000100f0, 0x400007bad0?)
	/Users/adaszko/repos/yarr-nanopi/src/storage/feed.go:142 +0x74
github.com/nkanaev/yarr/src/server.(*Server).handleFeedIcon(0x400014ac00, 0x40000cf380)
	/Users/adaszko/repos/yarr-nanopi/src/server/routes.go:183 +0xb4
github.com/nkanaev/yarr/src/server/router.(*Context).Next(...)
	/Users/adaszko/repos/yarr-nanopi/src/server/router/context.go:24
github.com/nkanaev/yarr/src/server/gzip.Middleware(0x40000cf380)
	/Users/adaszko/repos/yarr-nanopi/src/server/gzip/middleware.go:42 +0x244
github.com/nkanaev/yarr/src/server/router.(*Context).Next(...)
	/Users/adaszko/repos/yarr-nanopi/src/server/router/context.go:24
github.com/nkanaev/yarr/src/server/router.(*Router).ServeHTTP(0x400006aa80, {0x3d8d60?, 0x4000535b20}, 0x40001fd400)
	/Users/adaszko/repos/yarr-nanopi/src/server/router/router.go:81 +0x2b8
net/http.serverHandler.ServeHTTP({0x400059ecf0?}, {0x3d8d60, 0x4000535b20}, 0x40001fd400)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/http/server.go:2936 +0x2c0
net/http.(*conn).serve(0x4000092240, {0x3d90d8, 0x4000304f00})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/http/server.go:1995 +0x518
created by net/http.(*Server).Serve
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/http/server.go:3089 +0x4e8

goroutine 3326 [IO wait]:
internal/poll.runtime_pollWait(0xffff8a7a8968, 0x72)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/runtime/netpoll.go:306 +0xa0
internal/poll.(*pollDesc).wait(0x400014a000?, 0x40004f6071?, 0x0)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x400014a000, {0x40004f6071, 0x1, 0x1})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/internal/poll/fd_unix.go:167 +0x200
net.(*netFD).Read(0x400014a000, {0x40004f6071?, 0x26bf60?, 0x26fb80?})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/fd_posix.go:55 +0x28
net.(*conn).Read(0x4000234000, {0x40004f6071?, 0x1?, 0x400045c500?})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/net.go:183 +0x34
net/http.(*connReader).backgroundRead(0x40004f6060)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/http/server.go:674 +0x44
created by net/http.(*connReader).startBackgroundRead
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/http/server.go:670 +0xc8

goroutine 3115 [IO wait]:
internal/poll.runtime_pollWait(0xffff8a7a8e18, 0x72)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/runtime/netpoll.go:306 +0xa0
internal/poll.(*pollDesc).wait(0x400028a200?, 0x40002b4000?, 0x0)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x400028a200, {0x40002b4000, 0x1000, 0x1000})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/internal/poll/fd_unix.go:167 +0x200
net.(*netFD).Read(0x400028a200, {0x40002b4000?, 0x4000115a58?, 0x7462ec?})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/fd_posix.go:55 +0x28
net.(*conn).Read(0x4000284028, {0x40002b4000?, 0x4000115aa8?, 0x40005321b8?})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/net.go:183 +0x34
net/http.(*connReader).Read(0x40005321b0, {0x40002b4000, 0x1000, 0x1000})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/http/server.go:782 +0x224
bufio.(*Reader).fill(0x40002880c0)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/bufio/bufio.go:106 +0xfc
bufio.(*Reader).Peek(0x40002880c0, 0x4)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/bufio/bufio.go:144 +0x60
net/http.(*conn).serve(0x40000921b0, {0x3d90d8, 0x4000304f00})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/http/server.go:2030 +0x64c
created by net/http.(*Server).Serve
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/http/server.go:3089 +0x4e8

goroutine 3124 [select]:
database/sql.(*DB).conn(0x400010aea0, {0x3d9068, 0x4000024078}, 0x1)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/database/sql/sql.go:1335 +0x414
database/sql.(*DB).query(0x400010f578?, {0x3d9068, 0x4000024078}, {0x2f2cd1, 0x7b}, {0x400010f758, 0x1, 0x1}, 0xc8?)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/database/sql/sql.go:1721 +0x40
database/sql.(*DB).QueryContext.func1(0x0?)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/database/sql/sql.go:1704 +0x54
database/sql.(*DB).retry(0x400010f658?, 0x400010f630)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/database/sql/sql.go:1538 +0x4c
database/sql.(*DB).QueryContext(0xffff8a6306e8?, {0x3d9068?, 0x4000024078?}, {0x2f2cd1?, 0x40005318c0?}, {0x400010f758?, 0x400010f6f8?, 0x7f0690?})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/database/sql/sql.go:1703 +0x94
database/sql.(*DB).QueryRowContext(...)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/database/sql/sql.go:1804
database/sql.(*DB).QueryRow(0x101?, {0x2f2cd1?, 0x400010f788?}, {0x400010f758?, 0x4000305950?, 0x8?})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/database/sql/sql.go:1818 +0x4c
github.com/nkanaev/yarr/src/storage.(*Storage).GetFeed(0x40000100f0, 0x400007bad0?)
	/Users/adaszko/repos/yarr-nanopi/src/storage/feed.go:142 +0x74
github.com/nkanaev/yarr/src/server.(*Server).handleFeedIcon(0x400014ac00, 0x40000cf3c0)
	/Users/adaszko/repos/yarr-nanopi/src/server/routes.go:183 +0xb4
github.com/nkanaev/yarr/src/server/router.(*Context).Next(...)
	/Users/adaszko/repos/yarr-nanopi/src/server/router/context.go:24
github.com/nkanaev/yarr/src/server/gzip.Middleware(0x40000cf3c0)
	/Users/adaszko/repos/yarr-nanopi/src/server/gzip/middleware.go:42 +0x244
github.com/nkanaev/yarr/src/server/router.(*Context).Next(...)
	/Users/adaszko/repos/yarr-nanopi/src/server/router/context.go:24
github.com/nkanaev/yarr/src/server/router.(*Router).ServeHTTP(0x400006aa80, {0x3d8d60?, 0x4000535c00}, 0x40001fd700)
	/Users/adaszko/repos/yarr-nanopi/src/server/router/router.go:81 +0x2b8
net/http.serverHandler.ServeHTTP({0x40004f6060?}, {0x3d8d60, 0x4000535c00}, 0x40001fd700)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/http/server.go:2936 +0x2c0
net/http.(*conn).serve(0x40001ae120, {0x3d90d8, 0x4000304f00})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/http/server.go:1995 +0x518
created by net/http.(*Server).Serve
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/http/server.go:3089 +0x4e8

goroutine 3325 [IO wait]:
internal/poll.runtime_pollWait(0xffff8a7a90e8, 0x72)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/runtime/netpoll.go:306 +0xa0
internal/poll.(*pollDesc).wait(0x400028a300?, 0x400059ed01?, 0x0)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x400028a300, {0x400059ed01, 0x1, 0x1})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/internal/poll/fd_unix.go:167 +0x200
net.(*netFD).Read(0x400028a300, {0x400059ed01?, 0x26bf60?, 0x26fb80?})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/fd_posix.go:55 +0x28
net.(*conn).Read(0x4000284040, {0x400059ed01?, 0x1?, 0x400045cd20?})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/net.go:183 +0x34
net/http.(*connReader).backgroundRead(0x400059ecf0)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/http/server.go:674 +0x44
created by net/http.(*connReader).startBackgroundRead
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/http/server.go:670 +0xc8

goroutine 3114 [runnable]:
internal/poll.runtime_pollWait(0xffff8a7a8ff8, 0x72)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/runtime/netpoll.go:306 +0xa0
internal/poll.(*pollDesc).wait(0x400028a180?, 0x4000968000?, 0x0)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x400028a180, {0x4000968000, 0x1000, 0x1000})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/internal/poll/fd_unix.go:167 +0x200
net.(*netFD).Read(0x400028a180, {0x4000968000?, 0x4000251a58?, 0x7462ec?})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/fd_posix.go:55 +0x28
net.(*conn).Read(0x4000284020, {0x4000968000?, 0x4000251aa8?, 0x400059ee18?})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/net.go:183 +0x34
net/http.(*connReader).Read(0x400059ee10, {0x4000968000, 0x1000, 0x1000})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/http/server.go:782 +0x224
bufio.(*Reader).fill(0x4000530000)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/bufio/bufio.go:106 +0xfc
bufio.(*Reader).Peek(0x4000530000, 0x4)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/bufio/bufio.go:144 +0x60
net/http.(*conn).serve(0x4000092120, {0x3d90d8, 0x4000304f00})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/http/server.go:2030 +0x64c
created by net/http.(*Server).Serve
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/http/server.go:3089 +0x4e8

goroutine 3357 [IO wait]:
internal/poll.runtime_pollWait(0xffff8a7a8a58, 0x72)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/runtime/netpoll.go:306 +0xa0
internal/poll.(*pollDesc).wait(0x400028a000?, 0x400059ed91?, 0x0)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x400028a000, {0x400059ed91, 0x1, 0x1})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/internal/poll/fd_unix.go:167 +0x200
net.(*netFD).Read(0x400028a000, {0x400059ed91?, 0x26bf60?, 0x26fb80?})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/fd_posix.go:55 +0x28
net.(*conn).Read(0x4000284010, {0x400059ed91?, 0x1?, 0x40001fef50?})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/net.go:183 +0x34
net/http.(*connReader).backgroundRead(0x400059ed80)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/http/server.go:674 +0x44
created by net/http.(*connReader).startBackgroundRead
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/http/server.go:670 +0xc8

goroutine 3367 [runnable]:
internal/poll.runtime_pollWait(0xffff8a7a8d28, 0x72)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/runtime/netpoll.go:306 +0xa0
internal/poll.(*pollDesc).wait(0x400077a080?, 0x40004f62e1?, 0x0)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x400077a080, {0x40004f62e1, 0x1, 0x1})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/internal/poll/fd_unix.go:167 +0x200
net.(*netFD).Read(0x400077a080, {0x40004f62e1?, 0x26bf60?, 0x26fb80?})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/fd_posix.go:55 +0x28
net.(*conn).Read(0x4000010058, {0x40004f62e1?, 0x1?, 0x400022f400?})
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/net.go:183 +0x34
net/http.(*connReader).backgroundRead(0x40004f62d0)
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/http/server.go:674 +0x44
created by net/http.(*connReader).startBackgroundRead
	/opt/homebrew/Cellar/go/1.20.1/libexec/src/net/http/server.go:670 +0xc8
```

That’s at commit d2678be96d37a71ec34ac23207393f78dcceafc5

**Comment by adaszko** [comment]
It looks to me like a read from [`s.cache`](https://github.com/nkanaev/yarr/blob/d2678be96d37a71ec34ac23207393f78dcceafc5/src/server/routes.go#L181) isn’t being synchronized.

**Comment by nkanaev** [comment]
again, thanks!
